export default {
  appTitle: 'Note.SV',
  subtitle: "Salattu ja hajautettu salasanamanageri ja merkintäsäilö",
  password: 'Salasanat',
  settings: 'Asetukset',
  help: 'Apua',
  note: 'Merkinnät',
  balanceSatoshi: 'Saldo: {walletBalance} satoshia',
  charge: 'Lisää varoja',
  lockScreen: 'Lukitse näyttö',
  inputPassword: 'Syötä salasana avataksesi lukituksen',
  BiometricAuth: 'Biometrinen tunnistauminen',
  FaceIDAuth: 'Käytä Face ID:tä tunnistautumiseen ja lukituksen avaamiseen',
  TouchIDAuth: 'Käytä Touch ID:tä tunnistautumiseen ja lukituksen avaamiseen',
  unlock: 'Avaa lukitus',
  forgotPassword: 'Unohtunut salasana',
  day: 'Päivä',
  hours: 'Tuntia',
  minute: '{minute} minuutin jälkeen',
  minutes: '{minute} minuutin jälkeen',
  seconds: 'Sekuntia',
  Characters: '{length} merkkiä',
  UppercaseLetters: 'Isoja kirjaimia (A-Z)',
  LowercaseLetters: 'Pieniä kirjaimia (a-z)',
  IncludeNumbers: 'Liitä numeroita (0-9)',
  IncludeSymbols: 'Liitä symboleita',
  Intro: 'Esittely',
  CreateMasterWords: 'Luo pääsalasanat',
  ImportMasterWords: 'Tuo pääasalasanat',
  ScanAndImportMasterWords: 'Skannaa pääsalasanojen QR-koodi ja tuo ne',
  LockScreenPassword: 'Lukitusnäytön salasana',
  LockScreenPasswordAgain: 'Lukitusnäytön salasana uudelleen',
  error: 'Virhe. Ole hyvä ja yritä uudelleen.',
  'At least one rule for pools must be true': 'At least one rule for pools must be true',
  'Generate Password': 'Luo salasan',
  'App Version': 'Ohjelmaversio',
  'Auto Lock Screen': 'Lukitse näyttö automaattisesti',
  'Scroll back up': 'Skrollaa takaisin ylös...',
  status: {
    0: 'Paikallinen',
    1: 'Julkaistu',
    2: 'Vastaanotettu',
    3: 'Ketjussa'
  },

  'History Record': 'Merkintöhistoria',
  Return: 'Takaisin',
  Search: 'Hae',
  SearchAll: 'Kaikki',
  Share: 'Jaa(TODO)',
  'Sort By': 'Järjestä',
  title: 'Otsikko',
  time: 'Aika',
  AddNote: 'Lisää merkintä',
  AddPassword: 'Lisää salasana',
  AutoSaveDraft: 'Tallenna luonnos automaattisesti',
  SaveDraft: 'Tallenna luonnos',
  SaveSubmit: 'Synkronoi tallennus',
  Save: 'Tallenna',
  RequireVal: 'Pakollinen syöte',
  Content: 'Sisältö',
  CheckRule: 'Ole hyvä ja tarkista syötteesi',
  Submited: 'Lähetetty',
  EditNote: 'Muokkaa',
  EditPassword: 'Muokkaa',
  Delete: 'Poista',
  memo: 'Merkintä',
  Confirm: 'Vahvista',
  ConfirmDelete: 'Poista merkintä',
  ConfirmDraftDelete: 'Poista luonnos',
  fid: 'Käyttäätunnus tai sähköpostiosoite',
  pwd: 'Salasana',
  url: 'Kirjautumisen URL-osoite',
  otp: 'Kertakäyttöinen salasana',
  Copied: 'Kopioitu',
  'Copy Failed': 'Kopioiminen epäonnistui',
  Edit: 'Muokkaa',
  Close: 'Sulje',
  CloseHintForSaveDraft: 'Tallenna se luonnoksena?',
  Yes: 'Kyllä',
  No: 'Ei',
  UpdatedOn: 'Päivitetty',
  Settings: 'Asetukset',
  Language: 'Kieli',
  Account: 'Tili',
  BackupMasterWords: 'Varmuuskopioi pääasalasanat',
  ChangeLockPWD: 'Vaihda lukitusnäytön salasana',
  RemoveAccount: 'Poista tili',
  Remove: 'Poista',
  MasterWords: 'Pääsalasanat',
  Restart: 'Uudelleenkäynnistys',
  Verify: 'Vahvista',
  VerifyMasterWords: 'Vahvista pääsalasanat',
  MasterWordsVerified: 'Pääsalasanat vahvistettiin',
  MasterWordsFailed: 'Pääsalasanoja ei ole vahvistettu, ole hyvä ja yritä uudelleen',
  ChangePassword: 'Vaihda lukitusnäytön salasana',
  InputNewPassword: 'Uusi salasan',
  InputPasswordAgain: 'Uusi salasana (toista syöte)',
  Done: 'Valmis',
  MnemonicLanguage: 'Pääsalasanojen kieli',
  PasswordFailed: 'Ole hyvä ja tarkista salasana',
  PasswordChanged: 'Salasana vaihdettiin',
  ConfirmBackup: 'Vahvista varmuuskopiointi',
  BackupMasterWordsNow: 'Varmuuskopioi pääsalasanat nyt',
  SkipBackup:  'Ohita varmuuskopiointi',
  Withdraw: 'Nosta Satosheja',
  RequireCorrectAddress: 'Vaatii kelvollisen osoitteen',
  AddressFormat: 'Muoto',
  WithdrawAddress: 'Nosto-osoite',
  WithdrawAll: 'Nosta kaikki Satoshit',
  ContinueWithdraw: 'Jatka nostotapahtumaa',
  'Skip this step': 'Ohita tämä vaihe',
  InputMissMasterWords: 'Ole hyvä ja tarkista pääsalasanasi',
  ConfirmRemoveMessage: 'Vahvista POISTO, sitten luo uusi tili, tai tuo pääsalasanat',
  AddressMissing: 'Ole hyvä ja tarkista osoitteesi',
  Withdrawing: 'Nostetaan osoitteeseen <br/><span class="text-primary">{address}</span>',
  NoResults: 'Ei tuloksia',
  NoPasswordMessage: 'Salasanoja ei löytynyt',
  NoNoteMessage: 'Muistiinpanoja ei löytynyt',
  Alipay: 'Alipay',
  Wechatpay: 'Wechat Pay',
  Unionpay: 'Union Pay',
  'Money Button': 'Money Button',
  Wallet: 'Bitcoin SV -lompakko',
  ChargeAddress: 'Talletusosoite',
  ChargeAmount: 'Nostettava summa',
  USD: 'USD',
  RMB: 'RMB',
  'No Balance': 'Satosheja ei löytynyt, ole hyvä ja lisää varoja',

  IntroMessage: `<p>
  NoteSV käyttää korkeinta tietoturvatekniikkaa pitääksesi henkilötietosi, kuten salasanat, pankkitilien tiedot muut luottamukselliset tiedot turvassa.
</p>
<p>
Kaikki sisältö on salattu käyttämällä elliptisen käyrän epäsymmetristä salausalgoritmia, joka hajautetaan Bitcoin-nodeissa ympäri maailman. Vain sinä näet sisällön, eikä kukaan voi kurkistaa niihin. Tietoja ei koskaan menetetä tietokonevian vuoksi.
</p>
<p>
Ensin sinun on luotava tietojen palautusta varten pääsalasanati ja kirjattava ne <strong> kynällä ja paperilla </strong>. Pääsalasanat ovat ainoa avain, jolla voit palauttaa tilisi. Jos kadotat ne, tiliä ei voida palauttaa. Älä ota kuvakaappauksia tallentaessasi pääsalasanoja.
</p>`,

  MasterWordsMessage: `<p>
  Ole hyvä ja käytä kynää ja paperia pääsalasanojen tallentamiseksi, ja pidä ne sitten turvassa. Pääsalasanat ovat ainoa avain, jolla voit palauttaa tilisi. Mikäli kadotat ne, et voi palauttaa tiliäsi. Älä ota kuvakaappausta pääsalasanoista, sillä se voi avata mahdollisuuden tietojen hukkaamiseen tai varastamiseen.
</p>`,

  InputMasterWordsMessage: `<p>
  Ole hyvä ja kirjoita pääsalasanasi järjestyksessä, ja sitten klikkaa Vahvista-painiketta.
</p>
`,
  BackupMessage: `<p>
  Oletko varmuuskopioinut pääsalasanat? Ellet ole, et voi palauttaa tätä tiliä.
</p>`,
  InputAddressMessage: `<p>
  Kirjoita BSV-lompakkosi osoite, tai vaihto-osoite, ja tarkista, että se on oikein. Napsauta Nosta-painiketta ja nosta kaikki Satoshit.
</p>`,
  InputAddressHintMessage: `<p>
  Jos olet jo varmuuskopioinut tilisi, sinun ei tarvitse nostaa Satosheja. Uudelleenasennuksen yhteydessä pääsalasanoja voidaan käyttää tilin palauttamiseen.
</p>
`,
  ChargeMessage: `
<p>
Ohjelmiston käyttäminen maksaa vähän Satosheja. Kun lataat 10 euroa tilille, voit luoda yli 3000 turvattua dokumenttia.
    </p>

    <p>Ole hyvä ja valitse summa ja saldon latausmenetelmä</p>
`,
  ChargeWalletMessage: `<p>
  Jos sinulla on jo BSV:tä, voit lähettää jonkin verran yllä olevaan osoitteeseen. Jos sinulla ei ole BSV:tä, lataa saldoa muilla menetelmillä.
</p>
`,
  PasswordError: 'Virhe salasanassa.',
  ForgotPasswordTitle: 'Todellako unohtunut salasana?',
  ForgotPasswordMessage: 'Ole hyvä ja nollaa, sitten tuo varmuuskopioidut pääsalasanat tilin palauttamiseksi.',
  Cancel: 'Keskeytä',
  ResetSystem: 'Nollaa systeemi',
  ChargeSVCafeMessage: 'SV Cafe tukee Wechat Payta and Alipayta saldon lataamiseen. Ole hyvä ja valitse summa, ja sitten klikkaa kuvakenpainiketta.',
  'SV Cafe': 'SV Cafe',
  ChargeMoneyButtonMessage: 'Money Button on yksinkertaisin maksutapa satoshien lataamiseksi. Jos sinulla on Money Button -tili, valitse summa ja sitten pyyhkäise painiketta, ole hyvä',
  'Image Files': 'Kuvatiedostot',
  'Clear All': 'Tyhjennä kaikki',
  'Attach your files': 'Liitä kuvatiedostosi',
  nFiles: '{count} tiedostoa. ({size}) Suurin yhteensä {maxTotalSize} saatavilla',
  'Pick Files': 'Valitse tiedostot',
  Satoshi: ' Satoshi',
  'Dot Wallet': 'Dot Wallet',
  ChargeDotWalletMessage: 'DotWallet on maailmanlaajuisesti käytetyin BSV-lompakko. Se tarjoaa turvallisia ja luotettavia digitaalisten varojen hallintapalveluita miljoonille käyttäjille yli 150:ssä maassa ympäri maailman. Ole hyvä ja valitse summa ja klikkaa kuvakepainiketta.',
  ChargeFails: 'Saldon lataaminen epäonnistui, ole hyvä ja käytä toista maksutapaa',
  'checking-for-update': 'Tarkistetaan päivityksiä...',
  'update-available': 'Päivitys on saatavilla. Ladataan automaattisesti...',
  'update-not-available': 'Päivityksiä ei ole saatavilla.',
  'update-downloaded': 'Päivitys ladattu',
  'update-error': 'Virhe päivityksessä.',
  Syncing: 'Synkronoidaan tietoja',
  SyncFinished: 'Synkronointi valmis',
  Paymail: 'Paymail-tili',
  PaymailDesc: 'Vain sinun NoteSV-tunnukselle, ÄLÄ lähetä sähköpostia tähän osoitteeseen.',
  NoPaymal: 'Ei asetettu',
  NoLock: 'Älä lukitse koskaan',
  Online: 'Internet päällä',
  Offline: 'Internet pois päältä',
  AccountID: 'Tilitunniste',
  Name: 'Nimi',
  Email: 'Sähköpostiosoite',
  CheckAccountID: 'Tarkista tunniste',
  SaveAccount: 'Tallenna tili',
  AliasNoModify: "Kun tallennettu, tätä tilitunnistetta ei voi enää muokata",
  'id-already-exist': 'Tunniste on jo olemassa',
  'id-available': 'Tunniste on saatavilla',
  RequireAliasRule: 'Vaaditaan aakkosnumeerinen syöte',
  ServiceUnavailable: 'Palvelu ei ole nyt saatavilla',
  Saved: 'Tallennettu',
  PaymailAddress: 'Paymail-osoite',
  PaymailAddressMessage: 'TAI, voit ladata myös BSV Satoshia Paymail-osoitteeseen.',
  NoPaymailAddressMessage: 'Rekisteröi tili ladataksesi saldoa nopeasti',
  RegisterAccoun: 'Rekisteröi',
  'exceed-max-total-size': 'Ylittää suurimman sallitun koon (Enintään:{maxSize})',
  ChangePhoto: 'Vaihda kuva',
  Minimize: 'Kutista',
  Maximize: 'Laajenna',
  Reset: 'Nollaa',
  ChargeAlipayWechatMessage: 'SV Cafe tukee Wechat Payta and Alipayta saldon lataamiseen. Ole hyvä ja valitse summa ja klikkaa kuvakepainiketta, sitten skannaa QR-koodi kännykkäapilla.',
  Charged: 'Latasit nyt saldoa onnistuneesti',
  ChargeTimeout: 'Saldon lataamisen aikaraja ylittyi, ole ja hyvä ja yritä uudelleen',
  ResizeImage: 'Muuta kuvan koko automaattisesti',
  DeleteDraft: 'Hylkää luonnos',
  LockNow: 'Lukitse nyt',
  RegisterAccount: 'Rekisteröi tili'
}
